fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
                       
  symlinks:
    riemann: "#{source_dir}"
