---
language: ruby
sudo: true
dist: trusty
bundler_args: --without development
before_install:
  - wget https://apt.puppetlabs.com/puppet5-release-trusty.deb
  - sudo dpkg -i puppet5-release-trusty.deb
  - sudo apt-get update -qq
install:
  - sudo apt-get -qq install openjdk-8-jre wget
  - gem install pdk
  - wget -O riemann.deb https://github.com/riemann/riemann/releases/download/0.3.0/riemann_0.3.0_all.deb
  - sudo dpkg -i riemann.deb
before_script:
  - bundle install
  - bundle exec puppet --version
  - bundle exec puppet module build
  - bundle exec puppet module install pkg/*.tar.gz
rvm:
  - 2.1.9
  - 2.2.7
  - 2.3.4
  - 2.4.1
script:
  - pdk test unit
  - ./smoke/test
env:
  - PUPPET_GEM_VERSION="~> 4.9.0"
  - PUPPET_GEM_VERSION="~> 4.9.4"
  - PUPPET_GEM_VERSION="~> 4.10.0"
  - PUPPET_GEM_VERSION="~> 4.10.9"
  - PUPPET_GEM_VERSION="~> 4.10.10"
  - PUPPET_GEM_VERSION="~> 5.0.0"
  - PUPPET_GEM_VERSION="~> 5.0.1"
  - PUPPET_GEM_VERSION="~> 5.1.0"
  - PUPPET_GEM_VERSION="~> 5.3.5"
  - PUPPET_GEM_VERSION="~> 5.4.0"
#matrix:
#  exclude:
#  - rvm: 1.9.3
#    env: PUPPET_GEM_VERSION="~> 3.5.0"
