---
language: ruby
bundler_args: --without development
before_install:
  - rm Gemfile.lock || true
  - sudo apt-get update -qq
install:
  - sudo apt-get -qq install puppet riemann
  - bundle install
before_script:
  - mkdir -p ~/.puppet/modules
  - ln -s $PWD ~/.puppet/modules/riemann
  - puppet module install puppetlabs-stdlib
  - puppet module install puppetlabs-concat
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
script:
  - bundle exec rake test
  - ./smoke/test
env:
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.5.0"
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.7.1"
  - PUPPET_VERSION="~> 3.7.2"
  - PUPPET_VERSION="~> 3.7.3"
  - PUPPET_VERSION="~> 3.7.4"
  - PUPPET_VERSION="~> 3.7.5"
matrix:
  exclude:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.5.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 3.5.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.5.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.5.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.5.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.4.0"
