---
language: ruby
sudo: true
dist: trusty
bundler_args: --without development
before_install:
  - rm Gemfile.lock || true
  - wget https://apt.puppetlabs.com/puppet5-release-trusty.deb
  - sudo dpkg -i puppet5-release-trusty.deb
  - sudo apt-get update -qq
  - sudo gem install bundler
install:
  - sudo apt-get -qq install puppet openjdk-8-jre wget pdk
  - wget -O riemann.deb https://github.com/riemann/riemann/releases/download/0.3.0/riemann_0.3.0_all.deb
  - sudo dpkg -i riemann.deb
  - bundle install
before_script:
  - mkdir -p ~/.puppetlabs/etc/code/modules
  - ln -s $PWD ~/.puppetlabs/etc/code/modules/riemann
  - puppet module install puppetlabs-stdlib
  - puppet module install puppetlabs-concat
rvm:
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - 2.4.0
script:
  - pdk test unit
  - ./smoke/test
env:
  - PUPPET_VERSION="~> 4.1.0"
  - PUPPET_VERSION="~> 4.2.0"
  - PUPPET_VERSION="~> 4.2.1"
  - PUPPET_VERSION="~> 4.2.2"
  - PUPPET_VERSION="~> 4.2.3"
  - PUPPET_VERSION="~> 4.3.0"
  - PUPPET_VERSION="~> 4.3.1"
  - PUPPET_VERSION="~> 4.3.2"
  - PUPPET_VERSION="~> 4.4.0"
  - PUPPET_VERSION="~> 4.4.1"
  - PUPPET_VERSION="~> 4.4.2"
  - PUPPET_VERSION="~> 4.5.0"
  - PUPPET_VERSION="~> 4.5.1"
  - PUPPET_VERSION="~> 4.5.2"
  - PUPPET_VERSION="~> 4.5.3"
  - PUPPET_VERSION="~> 4.6.0"
  - PUPPET_VERSION="~> 4.6.1"
  - PUPPET_VERSION="~> 4.6.2"
  - PUPPET_VERSION="~> 4.7.0"
  - PUPPET_VERSION="~> 4.7.1"
  - PUPPET_VERSION="~> 4.8.0"
  - PUPPET_VERSION="~> 4.8.1"
  - PUPPET_VERSION="~> 4.8.2"
  - PUPPET_VERSION="~> 4.9.0"
  - PUPPET_VERSION="~> 4.9.1"
  - PUPPET_VERSION="~> 4.9.2"
  - PUPPET_VERSION="~> 4.9.3"
  - PUPPET_VERSION="~> 4.9.4"
  - PUPPET_VERSION="~> 4.10.0"
  - PUPPET_VERSION="~> 4.10.1"
  - PUPPET_VERSION="~> 4.10.2"
  - PUPPET_VERSION="~> 4.10.3"
  - PUPPET_VERSION="~> 4.10.4"
  - PUPPET_VERSION="~> 4.10.5"
  - PUPPET_VERSION="~> 4.10.6"
  - PUPPET_VERSION="~> 4.10.7"
  - PUPPET_VERSION="~> 4.10.8"
  - PUPPET_VERSION="~> 4.10.9"
  - PUPPET_VERSION="~> 4.10.10"
  - PUPPET_VERSION="~> 5.0.0"
  - PUPPET_VERSION="~> 5.0.1"
  - PUPPET_VERSION="~> 5.1.0"
  - PUPPET_VERSION="~> 5.2.0"
  - PUPPET_VERSION="~> 5.3.0"
  - PUPPET_VERSION="~> 5.3.1"
  - PUPPET_VERSION="~> 5.3.2"
  - PUPPET_VERSION="~> 5.3.3"
  - PUPPET_VERSION="~> 5.3.4"
  - PUPPET_VERSION="~> 5.3.5"
  - PUPPET_VERSION="~> 5.4.0"
#matrix:
#  exclude:
#  - rvm: 1.9.3
#    env: PUPPET_VERSION="~> 3.5.0"
