---
language: ruby
bundler_args: --without development
before_install:
  - rm Gemfile.lock || true
  - sudo apt-get update -qq
install:
  - sudo apt-get -qq install puppet
  - bundle install
before_script:
  - mkdir -p ~/.puppet/modules
  - ln -s $PWD ~/.puppet/modules/riemann
  - git clone https://github.com/puppetlabs/puppetlabs-stdlib ~/.puppet/modules/stdlib
  - git clone https://github.com/puppetlabs/puppetlabs-concat ~/.puppet/modules/concat
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
script:
  - bundle exec rake test
  - ./smoke/test
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.5.0"
  - PUPPET_VERSION="~> 3.6.0"
matrix:
  exclude:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.2.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.3.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.4.0"
