---
language: ruby
sudo: true
dist: trusty
bundler_args: --without development
before_install:
  - wget https://apt.puppetlabs.com/puppet5-release-trusty.deb
  - sudo dpkg -i puppet5-release-trusty.deb
  - sudo apt-get update -qq
install:
  - sudo apt-get -qq install openjdk-8-jre wget
  - wget -O riemann.deb https://github.com/riemann/riemann/releases/download/0.3.0/riemann_0.3.0_all.deb
  - sudo dpkg -i riemann.deb
before_script:
  - bundle install
  - bundle exec puppet --version
  - bundle exec puppet module build || bundle exec pdk build --force
  - bundle exec puppet module install pkg/*.tar.gz
script:
  - bundle exec rake lint
  - bundle exec rake validate
  - bundle exec rake spec
  - bundle exec ./smoke/test -d
matrix:
  include:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.4.5
    env: PUPPET_GEM_VERSION="~> 5.0"
  - rvm: 2.5.3
    env: PUPPET_GEM_VERSION="~> 6.0"
