#!/bin/sh

RV=$(ruby --version)

set_puppet_version()
{
	V=${1:-4.9.1}
	echo -n "Running tests using ${RV} and puppet "
	export PUPPET_GEM_VERSION="~> ${V}"
	bundle update puppet >/dev/null
	bundle exec puppet --version
}

for version in $GITLAB_CI_PUPPET_VERSIONS; do
	rm Gemfile.lock
	gem install bundler
  bundle install --without system_tests
	set_puppet_version $version
  bundle exec puppet module build
  bundle exec puppet module install pkg/*.tar.gz
	bundle exec rake lint
	bundle exec rake validate
	bundle exec rake spec
	./smoke/test
done

