#!/bin/sh -u

[ ! -d "./smoke" ] && { echo "No tests to run"; exit 0; }

should_succeed()
{
	$@
	case $? in
		0|2) :;;
		*) exit $?;;
	esac
}

should_fail()
{
	$@
	case $? in
		0|2) exit 8;;
		*) :;;
	esac
}

for manifest in $(find ./smoke -type f -name 'OK_*.pp'); do
	echo '*'
	echo '* Testing manifest `'$manifest'`'
	echo '*'
 	should_succeed puppet apply --detailed-exitcodes $manifest
	echo '*'
	echo '* Passed OK *'
done
for manifest in $(find ./smoke -type f -name 'NOK_*.pp'); do
	echo '*'
	echo '* Testing manifest `'$manifest'`'
	echo '*'
 	should_fail puppet apply --detailed-exitcodes $manifest
	echo '*'
	echo '* Failed OK *'
done
